### ISSUE TITLE
Not working as intended with stackmat timer v4

### ISSUE THREAD

**Issue by finki001** [mstiles92/stackmat#3]
It seems like the stackmat v4 timer does not send ready/unready/started/stopped commands properly

**Comment by stilesdev** [comment]
Hey there, sorry I missed this. I somehow didn't have notifications turned on for this repo.

If you're still looking to get this working, could you check whether your Stackmat timer works in cstimer or another browser-based timer?

I know it can be a pain to get the Stackmat timer recognized by any browser-based timer, so that is really the best way to narrow down whether it is an audio setting on your machine preventing this from working, or an actual issue with this library. I remember that setting this up on Windows sometimes took some extra trial and error with various Windows audio settings.

For reference, on my Manjaro KDE machine using Chrome, my Stackmat v4 timer works perfectly both in cstimer and with this library.

I'll close this issue for now since it's been so long, but feel free to leave a comment if you're still having a problem specific to this library and I'll reopen it.
